# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vbguest.auto_update = false

  # OS
  config.vm.box = "centos6.5"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  #ssh
  config.ssh.insert_key = false

  # Networking
  config.vm.hostname = "sitter"
  config.vm.network :private_network, ip: "192.168.33.40"

  # Source Folder
  config.vm.synced_folder "./", "/share", \
      create: true, owner: "vagrant", group: "vagrant", \
      mount_options: ["dmode=777,fmode=777"]

  # Provision
  config.omnibus.chef_version = :latest

  # Chef
  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = ["../../cookbooks/"]

    chef.add_recipe "nginx::default"
    chef.add_recipe "php::php70-fpm"
    chef.add_recipe "mysql::default"
    chef.add_recipe "php::composer"
    chef.add_recipe "php::phpunit"
    chef.add_recipe "phpmyadmin::php70"
    chef.add_recipe "ruby::default"
    chef.add_recipe "nodejs::default"
    chef.add_recipe "redis::default"

    chef.json = {
        :nginx => {
            :root => "/share/sitter/public",
            :nginx_conf => "nginx.conf",
            :conf => "laravel/default.conf",
            :phpmyadmin => {
                :enabled => true,
                :port => 9999
            }
        },
        :mysql => {
            :user => "sitter",
            :password => "sitter",
            :database => "sitter"
        },
        :php => {
            :xdebug => true,
            :xdebug_remote_host => "192.168.33.1"
        }
    }
  end

end

