# -*- mode: ruby -*-
# vi: set ft=ruby :

ipaddr = "192.168.33.10"

Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vbguest.auto_update = false

  # OS
  config.vm.box = "centos6.5"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  #ssh
  config.ssh.insert_key = false

  # Networking
  config.vm.hostname = "wordpress"
  config.vm.network :private_network, ip: ipaddr

  # Source Folder
  config.vm.synced_folder "./", "/share", \
      create: true, owner: "vagrant", group: "vagrant", \
      mount_options: ["dmode=777,fmode=777"]

  # Provision
  config.omnibus.chef_version = :latest

  # Chef
  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = ["../cookbooks/"]

    chef.add_recipe "mysql::default"
    chef.add_recipe "wordpress::setup-proto"
    chef.add_recipe "php::composer"
    chef.add_recipe "php::phpunit"
    chef.add_recipe "phpmyadmin::default"

    chef.json = {
        :mysql => {
            :user => "wordpress",
            :password => "wordpress",
            :database => "wordpress"
        },
        :nginx => {
            :root => "/share/wordpress",
            :aliases => [
                {
                    :location => "/phpMyAdmin",
                    :alias => "/usr/share/phpMyAdmin/",
                    :index => "index.php"
                }
            ]
        },
        :php => {
            :xdebug => true
        },
        :wordpress => {
            :version => "4.4",
            :install_user => "nginx",
            :install_path => "/share/wordpress",
            :dbname => "wordpress",
            :dbuser => "wordpress",
            :dbpass => "wordpress",
            :dbhost => "127.0.0.1",
            :title => "test wordpress",
            :url => ipaddr,
            :admin_user => "admin",
            :admin_password => "admin",
            :admin_email => "takayuki_imanishi@petgo.co.jp",
            :plugins => []
        }
    }
  end

end
